### ISSUE TITLE
Dashboard (Load Wallet replacement)

### ISSUE THREAD

**Issue by molnard** [zkSNACKs/WasabiDesign#10]
In v1.1.11 we got 2 places to load the wallet:

1. LoadWallet tab in WalletManager.
2. WalletExplorer.

WalletExplorer seems extremely useful for handling the wallet related operations, like opening wallets, so basically that is the place where we should handle wallet related operations. 

However, now is the questions:

- What to do with the LoadWallet tab?
- Provide a better startup screen to the user. 
- Autoload favorite wallet?
- New section? 

Few ideas:
https://github.com/zkSNACKs/WalletWasabi/issues/3356
https://github.com/zkSNACKs/WalletWasabi/issues/1329
https://github.com/zkSNACKs/WalletWasabi/issues/1369
https://github.com/zkSNACKs/WalletWasabi/issues/740

The business logic is pretty much ready so we have to figure out the interface. 
So unleash your creativity and let's design Wasabi's new welcome screen.

**Comment by molnard** [comment]
Pinging @kravens @Transisto @dennisreimann @xavierfiechter @MaxHillebrand @UkolovaOlga

**Comment by kravens** [comment]
I already intuitively double clicked my wallet in the Wallet Explorer, so phase out the Load Wallet button/tab (keep a clear Generate/Import Wallet tab).

Auto-load if only 1 wallet.json present (for new users) and add possibility to close wallets and manage tabs better. Could colour code each wallet with the corresponding tabs as example, with various colour scheme matching hues?
*reserved for a drawing

Present a welcome/news panel with Bitcoin only news (new Core/knots versions) and new Wasabi feature guides directly from WasabiDocs.

**Comment by ghost** [comment]
- I am in favor of removing the `Load Wallet` tab completely, and relying only on the `Wallet Explorer` to load and navigate the wallets.
- I am not against having a `News` tab, but my opinion depends on what will be placed on there, I don't know what would be good.
- If there is only one wallet, then this should be loaded automatically. [no-brainer I believe]
- If there are multiple wallets, then there can be different ways of handling it. I believe this is a good way of doing it, and it can be done before consensus on a `News` tab is reached.
-- Auto-load the last active wallet.
-- Have a setting with "priority wallet" which will be loaded every time at first

[I'm not saying anything about the color scheme in the tabs, as this issue is specifically about loading the wallets / start screen]

**Comment by molnard** [comment]
I created a sketch in Figma. It is not a prototype, neither a design. Some icons and images were just put there as a placeholder and functions like pin/unpin or load on startup put there as a text instead of an icon. 

Take a look at here: 
https://www.figma.com/file/OdJSeT7gDRRdxzz4zbeMDf/Startup?node-id=1%3A2

More suggestions:

- Want to learn more? Read our user-manual (link to docs)
- Add our logo somewhere

**Comment by molnard** [comment]
Current visual studio "splash screen"

![image](https://user-images.githubusercontent.com/9844978/81480931-07c8b880-922d-11ea-853c-ebe2f0709d1e.png)

**Comment by ghost** [comment]
That's a good design, thanks @molnard!

However, there is a duplication of `Hardware Wallet` on both sides of the screen. 

Also, the `Show all network` doesn't make much sense, as any wallet can be loaded on either mainnet or testnet or regtest.

Further, I think the feature to auto load a wallet means to skip the this start screen altogether and immediately jump into the wallet tab. 

In general, the left side looks more like a mix of settings [which wallets are auto loaded and pinned] and then a list of wallets [local, hardware, watch only], so it's not really different to the current load tab...

Do you intend to have the `Wallet Explorer` on the right side of the screen still? Or is this removed in this tab?

**Comment by molnard** [comment]
> That's a good design, thanks @molnard!
> 
> However, there is a duplication of `Hardware Wallet` on both sides of the screen.
> 

The right side is for adding. The left side is to load.

> Also, the `Show all network` doesn't make much sense, as any wallet can be loaded on either mainnet or testnet or regtest.
> 

Yes that is true, but I do not want to see my Test and Reg net wallets when I am on main net. The filtering can be easily done by the last network parameter in wallet file.

> Further, I think the feature to auto load a wallet means to skip the this start screen altogether and immediately jump into the wallet tab.

Which is the wallet tab?

> 
> In general, the left side looks more like a mix of settings [which wallets are auto loaded and pinned] and then a list of wallets [local, hardware, watch only], so it's not really different to the current load tab...

It looks better and gives you more information about what to do, next.

> 
> Do you intend to have the `Wallet Explorer` on the right side of the screen still? Or is this removed in this tab?

When there is not wallet loaded, wallet explorer will be hidden.

**Comment by ghost** [comment]
> The right side is for adding. The left side is to load.

Oh, ok. This was not instantly clear to me. I'm not against the idea though. 

> Yes that is true, but I do not want to see my Test and Reg net wallets when I am on main net. The filtering can be easily done by the last network parameter in wallet file.

Ok, a good point. Haha, I'm just used to having multiple VMs for this. But it's alright if Windows is not powerful enough for this feature ;)

> Which is the wallet tab?

That tap that was last opened in the wallet, for example the coinjoin tab. 

> When there is not wallet loaded, wallet explorer will be hidden.

But my thinking is, that we already have a great way of loading wallets with the explorer. So adding a different way of loading the wallet is UX confusion and clutter. The first time I must load the wallet on this start screen, the second time I must load it on the wallet explorer.

This is why I think that the start screen should not do wallet load at all, this should be done only in the explorer.

**Comment by molnard** [comment]
We cannot do that. Showing only the wallet explorer the user won't figure out that he should load there. 

Wasabi will show only one way to load the wallet. The only one will be visible, the wallet explorer on the right or the Startup screen.

**Comment by Transisto** [comment]
With coin control I don't think many people use that many wallet to be
confused.

What's a bit intimidating is how big the expected list of wallet is.

Having a giant load button next to each one of them wouldn't take much
space.

**Comment by ghost** [comment]
@molnard from what I have heard from users, and from I use the wallet now personally, after the introduction of multi wallet / the wallet explorer, this has become the go to way of switching between tabs and loading wallets. 

So, I think by now it is clear that a double click on the wallet explorer loads the wallet. 

I think we can stick with managing the wallets ONLY in the explorer, and thus reduce UX clutter and multiple ways to achieve the same thing.

**Comment by ghost** [comment]
what is it that the user wants when for the **very first time he opens the wallet**?

then of course it is to **generate a new wallet**, and we already show the generate wallet screen here - this is perfect.

---

but, what about when he opens wasabi afterwards, for the every day use?
I'd say he wants to instantly work with the wallet, see how much bitcoin is in there, and then send receive coinjoin or check the history. we already have that the last opened tab is opened again, this is great too.

---

I'm now looking at the figma scatch...

### left side

- auto load wallets
-- I think this should be in the settings, the user doesn't want to see this all the time, it's a set it and forget it kinda thing
- pinned wallets
-- I think this could just be a right click context menu option in the wallet explorer, so that this wallet is always on top of the list
- local / hardware / watchonly wallets
-- we already have this in the wallet explorer, but here with nice icons and such. so, this is again another list that shows the same thing.

### right side

- create wallet
-- this feature is used by most users only very rarely, maybe not at all after the first wallet generation. So I don't think the user needs to see it on every single start. It might as well be in the top menu bar.
- recover wallet
-- this feature is even less used than create wallet, in fact, I haven't used it once on mainnet... So again, I think this would clutter the start screen with something that is very rarely used.
- hardware wallet
-- this is only useful for the very first import of a hardware wallet, so somewhat similar with the frequency as the create wallet, but still less often. Again, i think this can be hidden in a menu, and shouldn't be shown all the time at every start to the user.

so, when looking at this screen, I as a user, will do the same thing all the time, on pretty much every start, and this is to click on my main wallet.
99.9% of the time, I will not do anything else.

and then I'm thinking, why show the screen at all?
why not immediately jump into the auto loaded wallet last tab?

all other wallets can be loaded in the explorer

new wallets can be created / recovered in the menu bar

**Comment by ghost** [comment]
#### I think we can get rid of the `Wallet Manager` altogether!

The `Wallet Manager` has functions that are either already in the UX elsewhere, or that can be moved somewhere.

![screenshot_20200520_213702](https://user-images.githubusercontent.com/30683012/82489616-3de62200-9ae2-11ea-8c2f-f4d33d123c82.png)

Regarding `Generate Wallet` and `Recover Wallet`, we already have this in the `File` menu. I think this can be kept here without any changes.

However, I think the `Load Wallet` can be removed from this menu. Again, I envision that the `Wallet Explorer` is the ONLY way to load and navigate between wallets.

![screenshot_20200520_213142](https://user-images.githubusercontent.com/30683012/82489158-73d6d680-9ae1-11ea-96a0-b3436d8c26d7.png)

The `Wallet Manager` also has these three options, so this is triple redundant.

The `Test Password` can be a right click context menu in the `Wallet Explorer`, for each of the wallets, where it then opens a popup box where the user types in the password. It could be a tab too, as it is now, but that's off topic. See #19.

And finally the `Hardware Wallet`, which is a bit of a bigger topic. But the gist is, it could be imported in the `Tools` menu, and then loaded in the `Wallet Explorer`.

In the `Tools` menu, I think that the `Wallet Manager` can be removed too. This has the `Load Wallet` [obsolete by the `Wallet Explorer`] and the `Generate Wallet` and `Recover Wallet` [already in the `File` menu], so the entire `Wallet Manager` is obsolete and can be de-cluttered.

![screenshot_20200520_213500](https://user-images.githubusercontent.com/30683012/82489893-ad5c1180-9ae2-11ea-9061-6f81d8594875.png)

**Comment by ghost** [comment]
Regarding auto-loading wallet, checkout https://github.com/bitcoin/bitcoin/pull/15937

> Bitcoin Core #15937 updates the createwallet, loadwallet, and unloadwallet RPCs to provide a load_on_startup option that will add the wallet’s name to the list of wallets automatically loaded on start up (or, if the option is set to false, remove the wallet’s name from that list). It’s expected that a future PR will allow the GUI to add or remove wallet names from the same list.

~ @bitcoinops [111](https://bitcoinops.org/en/newsletters/2020/08/19/)

**Comment by molnard** [comment]
### Priorization

- Merge Avalonia 0.10
- Implement this Startup screen

### Do we want to do the redesign?

The team approved to do it. 

### Display it instead of Load wallet Tab only?

No, display it instead of the whole Wallet Manager. Load Wallet tab has to be removed from the code.

### News section

- (con) Content generation pressure
- (con) For news, there is the blog section
- (pro) Could open a channel where the essential news can be communicated with the users 
- Rename News to Updates 

### Start screen content

- Don't want guides regarding the software
- Welcome screen should have a GUI that is super intuitive, what the users need to click on. 

# Dashboard idea

- The first screen is the generate a wallet like it is working now.  

### Update section

- Updates sections like in the screenshot
  - Announcements
  - Security vulnerabilities
  - Larger features
  - Short as a tweet, title, and date, no expandable things - the news is 3 lines of thing. If the link is added then Read more appears and a click will open a browser. 
  - Add a second option to communicate beside twitter and other 3rd parties. 
- Recently opened wallets. With all wallets or only the most recent ones?
- News, Hardcoded to the backend
  - Create updates.json into the backend repository and the backend should pick up the new file and serve that
  - Add this file to git repo to have the same review procedure as any other source code change 
- On the right side of the screen

### Open wallet section

- Play button(triangle) next to the wallet name as Load wallet functionality
- 3 wallets at maximum

### Common Tasks

- Put wallet manager functionalities there, generate, recover
- Simplest look buttons

## General concepts

- No pinning
- No fancy looking buttons
- Play button should be added to the wallet explorer, right side
- If the first wallet is loaded, jump to the wallet tabs
- Recently opened items look the same as the common tasks link buttons. 
- Recently opened wallet items just clickable links it became not clickable after the wallet started the load. Users can observe and learn wallet loading animation starts in the wallet explorer. 
- Multi wallet feature is not a priority for most of our users, keep it simple, and do not spend extra time on it.

**Comment by nopara73** [comment]
# Specification

![image](https://user-images.githubusercontent.com/9156103/91562066-de977980-e93c-11ea-9b01-a55c0b94b957.png)

## Context

- If the user has at least one wallet created, then this is the default screen
- Otherwise Tools/Dashboard
- Load Wallet tab should be removed completely
- Play buttons should be added to the Wallet Explorer to make it obvious one can load wallet from there

## Renamings (compared to the screenshot)

- "Welcome!" -> "Dashboard"
- "Wasabi News" -> "Updates"
- "Common Tasks" -> "Common Actions"

### Updates

- Title, Description, Date, (optional) Read more...
- The "Read more..." opens up a link to an online resource.
- The source of the updates is the Wasabi backend.
- Updates are stored in a `ClientUpdates.json` file under source control, but they aren't fetched from here.
- The `ClientUpdates.json` the backend serves must be manually updated for new update items (or modifying old ones.)

### Recently Opened

- 3 recently opened wallets as a list of links.
- The wallet's format is: "Wallet Name (STATUS)" where STATUS can be: "opened 3 days ago", "opening...", "open"
- if STATUS >= "opening..." then the wallet link should become unclickable and grayed out
- After the wallet is opened, the dashboard does not have to automatically close like in the Wallet Manager Case, but the selected tab must jump regardless.

### Common Actions

- A list of common actions, all pointing to specific tabs.
- List of actions: "Generate Wallet", "Recover Wallet", "Manage Hardware Wallets" 
- If a user clicks on an action, new tab will open.

**Comment by molnard** [comment]
https://github.com/zkSNACKs/WalletWasabi/issues/4253

**Comment by molnard** [comment]
@jmacato can you give me a status update on this?

**Comment by jmacato** [comment]
@molnard Currently waiting for 0.10 to be done, all the pieces are ready to be built upon after we merge 0.10
