### ISSUE TITLE
Multi-wallet UX discussion

### ISSUE THREAD

**Issue by jmacato** [zkSNACKs/WasabiDesign#8]
This tracks our discussion for implementing the UI for Multi-wallet support.

**Comment by jmacato** [comment]
My mockup for the integrated wallet tab idea: 
![Screenshot from 2020-03-24 16-08-31](https://user-images.githubusercontent.com/16554748/77437940-3545d800-6e20-11ea-8279-b4539fe2f724.png)


and prior discussion to the topic:
https://github.com/zkSNACKs/WalletWasabi/pull/2636

**Comment by danwalmsley** [comment]
I think the immediate plan should be:

- Coordinate selected tab with selection in WalletExplorer.
- Group tabs by wallet
- Colour code tabs by wallet
- non-wallet tabs docked to the right side of the tab area.
- Improve tab area to handle when there are more tabs than can fit horizontally.
- Consider making use of dock

After that we should consider more drastic UI changes.

**Comment by lontivero** [comment]
During the first discussions I understood something similar to what @jmacato shared above, one tab by wallet. But after some more back and forth I think we decided to go for individual tabs that could be visually identified by header color to know what wallet they belong to. Is this still the general agreement?

**Comment by ghost** [comment]
I don't really like @jmacato suggestion [here](https://github.com/zkSNACKs/WasabiDesign/issues/8#issuecomment-603277310) of adding a new menu bar to the left. But the one tab per wallet idea is good.

I think that instead of adding a new menu on the left side, we should stick with the wallet explorer on the right side. So, basically, keep it exactly how it is now, with the send, receive, coinjoin and advanced menu. Show these options for any wallet that is loaded, and allow to collapse these options too. 

Then, only show one tab for each wallet, and display whatever was selected in the right hand wallet explorer. 

This way, we do not break user space this much, because the wallet explorer was already there.

The "one tab per wallet" idea will be difficult for things like the details tabs - as these should be new tabs alongside the "main" wallet tab. Thus, color coding each wallet tab will still make sense. So, there is always one "main" wallet tab, in a unique color, and there can be optional detail tabs in the same color.

**Comment by lontivero** [comment]
I would prefer no tabs at all and enable docking panels in case you need to work with more than one view at a time.

**Comment by danwalmsley** [comment]
> I would prefer no tabs at all and enable docking panels in case you need to work with more than one view at a time.

The way the dock works you need the tabs to create that situation. The tab is the part that you drag to create a docking.

Of course we could create our own interactions to allow docking that don't use tabs. not sure what it would look like however.

**Comment by ghost** [comment]
yes @lontivero, and the concept of "one tab per wallet" should work very nice with the docking concept too...

**Comment by ghost** [comment]
I have now been playing with the multi wallet explorer some more. And I do believe that a general [though not a strict] concept of "one tab per wallet" makes a lot of sense. I have several reasons for this:

- The right hand wallet explorer is turning out to be a great way to navigate Wasabi. It shows all the wallets, and for all open ones the `send`, `receive`, `coinjoin`, `history` and `advanced` sections. 
- Here I clearly see, even without color coding, which `send` belongs to which wallet, because it is all nicely ordered.
- There could be one "main" tab for each wallet, that displays what ever I press in the wallet explorer. So, Wallet 1 is blue, and when I click `send` it shows the coinlist in the blue tab, when I click `receive` it shows the addresses in the blue tab etc. Wallet 2 is red, so it shows the main tab in red. 
- However, it is not strictly "one tab per wallet" but rather, a "main" tab [see above] and there can be other tabs of the same wallet, like for example a `coin details` or `history` tab. But, each of these additional tabs, are still in the same color as the wallet [blue for 1, red for 2, etc]. This way, it is still easy to see, that this `coin details` is from wallet 1.

**Comment by molnard** [comment]
Color coding, mockup: 

![image](https://user-images.githubusercontent.com/9844978/77650451-cf666700-6f6b-11ea-83b0-7f82764239a5.png)

**Comment by ghost** [comment]
Interesting @molnard . But I don't like the box, it doesn't align with the tab and text. Maybe the whole tab has the color, and a different shade of the color when it is selected?

**Comment by lontivero** [comment]
I believed that coloring the tabs would make it easy to identify the wallet/tab belonging but now that I see it, it does not. I have to check the color on the tab and then search with my eyes the wallet with the exact same color or in the other way around.

This work was necessary @molnard, otherwise I would have never realized this is a bad idea. I think it can work if implemented together with the tabs/wallets selection pairing/synchronization. But in isolation it will not work.

**Comment by bharmat** [comment]
I agree with Lucas, color coding prior to seeing it sounded like a good solution, but in practice, it is probably even more confusing, especially for color-blinds. :) So far I prefer Jumar's initial "one tab by wallet" idea. I think the point here is to make it clear for the user which wallet is he dealing with.  If we create endless tabs on the top it is going to be confusing after a while even if its color coded or differentiated in any ways.

**Comment by bharmat** [comment]
One more idea came up while discussing with @molnard. How about including the icon of the tab type (send, receive, etc.) followed by the wallet name, while keeping the current functionality of highlighting the wallet in the explorer. The original idea was to write both the tab type and wallet name, but including only the icon would shorten this. Can someone make a quick mockup about this so we could see how it would look like? Maybe even an abbreviation of the wallet name could be shown, by lets say showing only the first 5-6 characters.

**Comment by lontivero** [comment]
We tried that with the `Coin Details` tab and it does not work. The tab's title should be really really short (no longer than let say 12 chars):

![image](https://user-images.githubusercontent.com/127973/77946553-e2917380-7298-11ea-86ba-fdce5ae1b47e.png)

**Comment by ghost** [comment]
How about having the icon [send, receive, coinjoin, history] and then the name of the wallet in the tab?

so `[send icon] cold storage`

**Comment by bharmat** [comment]
This is what I meant with my previous comment.

**Comment by ghost** [comment]
@transisto brings up two good points [ħere](https://github.com/zkSNACKs/WalletWasabi/issues/3510#issuecomment-610656244). 

- A mockup of having the icon and wallet name in the tab, as Balint suggested
- Having the Receive tab show `Receive to -Wallet Name-`, which I think is a very important addition.

![image](https://user-images.githubusercontent.com/30683012/78765870-ddaf7c80-7988-11ea-83cd-f313d2791c9a.png)

**Comment by molnard** [comment]
Update on this: 
@MaxHillebrand has reported that users got confused with the current solution. So we need to add UI elements that clarify this more.

**Comment by ghost** [comment]
I have now watched several users interact with the new Wasabi multi wallet support, and a vast majority of them are using the `Wallet Explorer` intuitively, even at first start to load the wallet, and then especially when switching between wallets, or even tabs within a wallet.

I really think we can leverage this `Wallet Explorer` fully, meaning
- remove `Load Wallet` tab
- "one tab per wallet" where the view can be changed from the explorer

**Comment by ghost** [comment]
can this be closed?

**Comment by molnard** [comment]
This problem is still not solved. Why closing this?

**Comment by jmacato** [comment]
Obsoleted by the new Fluent Design
